# Generated by Django 3.2.9 on 2021-11-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeDnsServer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('name', models.CharField(max_length=100, null=True)),
                ('as_number', models.IntegerField()),
                ('as_org', models.CharField(max_length=256)),
                ('country_code', models.CharField(max_length=10, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('version', models.CharField(max_length=512, null=True)),
                ('error', models.BooleanField(default=False, null=True)),
                ('dnssec', models.BooleanField(null=True)),
                ('reliability', models.DecimalField(decimal_places=2, max_digits=3)),
                ('checked_at', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'de_dns_servers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DeDnsServerRaw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('name', models.CharField(max_length=100, null=True)),
                ('as_number', models.IntegerField()),
                ('as_org', models.CharField(max_length=256)),
                ('country_code', models.CharField(max_length=10, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('version', models.CharField(max_length=512, null=True)),
                ('error', models.BooleanField(default=False, null=True)),
                ('dnssec', models.BooleanField(null=True)),
                ('reliability', models.DecimalField(decimal_places=2, max_digits=3)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'de_dns_servers_raw',
                'managed': True,
            },
        ),
    ]
