# Generated by Django 3.2.9 on 2021-11-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_dns_servers', '0003_auto_20211108_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=6)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_tokens',
                'managed': True,
            },
        ),
    ]
