# Generated by Django 3.2.9 on 2021-11-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_dns_servers', '0004_apitoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='token',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
