# Generated by Django 3.2.9 on 2021-11-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_dns_servers', '0005_alter_apitoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='revoked_at',
            field=models.DateTimeField(null=True),
        ),
    ]
